# f = open ('C:\PythonPractice\myPython.txt', "r")
# print (f.read())
f = open ('C:\PythonPractice\myPython.txt', "w")
f.write('')
f.close()
f = open ('C:\PythonPractice\myPython.txt', "r")
print(f.read())

# f = open ('C:\PythonPractice\myPython.txt', "r")
# print(f.read())
